### ISSUE TITLE
ebuild for slurm

### ISSUE THREAD

**Issue by notdodo** [alem0lars/apo#2]
**Github**: https://github.com/mattthias/slurm

## Description: 

yet another network load monitor

slurm started as a FreeBSD port of the Linux ppp link monitor called pppstatus
by Gabriel Montenegro. Hendrik Scholz ripped of the ppp dependent parts and the
email checks to turn in into a generic network load monitor for *BSD, Linux,
HP-UX and Solaris.

## Example:
![screenshot from 2017-02-19 21-01-13](https://cloud.githubusercontent.com/assets/6991986/23106118/df972ac8-f6e8-11e6-8322-d34eb91a2208.png)

**Comment by alem0lars-yr** [comment]
Ebuild is already present in the official `gentoo` tree:

```
❯ eix -s slurm
* net-analyzer/slurm
     Available versions:  0.3.3-r2 ~0.4.3
     Homepage:            https://github.com/mattthias/slurm
     Description:         Realtime network interface monitor based on FreeBSD's pppstatus
```
